name: Workflow Comentarios PR

on:
  issue_comment:
    types: [created]

jobs:
  mensaje:
    if: github.event.issue.pull_request != null
    runs-on: ubuntu-latest
    steps:
      - run: echo "Comentario en PR detectado"
